### ISSUE TITLE
Rename of vel_t members.

### ISSUE THREAD

**Issue by Slaxzer96** [martinandrovich/rb-pro5#4]
The current name of the members are confusing.

**Comment by Slaxzer96** [comment]
done with renaming.

**Comment by martinandrovich** [comment]
> done with renaming.

Please specify what the members have been renamed to.

**Comment by martinandrovich** [comment]
Just checked the file; are `.speed` and `.dir` sufficiently descriptive? Or should be try something like:

`.delta_dir` and `.delta_ang`  _or_ `.dir_vel` and `.rot_vel`?

**Comment by Slaxzer96** [comment]
How about;
Velocity and angular_velocity.

**Comment by martinandrovich** [comment]
> How about;
> Velocity and angular_velocity.

Well, technically they're both one-dimensional quantities, being it's a `translational_delta` and `rotational_delta`, right?

**Comment by martinandrovich** [comment]
How about:
a) `.fwd_vel` and `.ang_vel`
b) `vel_t::translational` and `vel_t::rotational`?

or maybe abbreviate b?

**Comment by Slaxzer96** [comment]
Huy.
.velocity and .ang_vel
This issue is closed.

**Comment by martinandrovich** [comment]
Since the velocity type already specifies that it contains information about velocities, it would make sense to specify which types of velocities, i.e. `vel_t::trans` and `vel_t::ang`.

Also:
![Imgur](https://i.imgur.com/DPZCuWy.png)

**Comment by Slaxzer96** [comment]
ye lets go with those.
